"""added ReportsOrm

Revision ID: a76881fc922e
Revises: 7ece31ece19e
Create Date: 2025-02-28 13:26:08.129565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a76881fc922e"
down_revision: Union[str, None] = "7ece31ece19e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
